<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_library</name>
   <tag></tag>
   <elementGuidId>f4c48b8b-6d2f-400b-a752-6e393ad1d658</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tp-yt-iron-icon[@id='icon']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>tp-yt-iron-icon</value>
      <webElementGuid>3e38074d-b543-4a07-9a89-91276de57bd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>icon</value>
      <webElementGuid>9a63c277-edb1-4bf4-8d9c-862def88b894</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>style-scope tp-yt-paper-icon-button</value>
      <webElementGuid>7f46c439-9787-421f-8faa-2f3c4a5b5c94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;layout&quot;)/ytmusic-nav-bar[@class=&quot;style-scope ytmusic-app&quot;]/div[@class=&quot;center-content style-scope ytmusic-nav-bar&quot;]/ytmusic-search-box[@class=&quot;style-scope ytmusic-nav-bar&quot;]/div[@class=&quot;search-container style-scope ytmusic-search-box&quot;]/div[@class=&quot;search-box style-scope ytmusic-search-box&quot;]/tp-yt-paper-icon-button[@class=&quot;search-icon style-scope ytmusic-search-box&quot;]/tp-yt-iron-icon[@id=&quot;icon&quot;]</value>
      <webElementGuid>c6a16424-4620-4ca2-9fe8-68ff16e0f8f3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//tp-yt-iron-icon[@id='icon']</value>
      <webElementGuid>5903b756-4b96-4568-b942-a1f4aa7b7b57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ytmusic-app-layout[@id='layout']/ytmusic-nav-bar/div[2]/ytmusic-search-box/div/div/tp-yt-paper-icon-button/tp-yt-iron-icon</value>
      <webElementGuid>390ecead-e5f4-4f41-9fd3-dfbdcd87da1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Library'])[1]/following::tp-yt-iron-icon[1]</value>
      <webElementGuid>4b3f4c96-13f7-48bc-984a-54ae1e0c3634</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Explore'])[1]/following::tp-yt-iron-icon[1]</value>
      <webElementGuid>19e7249b-b964-4fcd-ace8-70cd2976b832</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign in'])[1]/preceding::tp-yt-iron-icon[11]</value>
      <webElementGuid>f96b0f20-8667-4021-82ec-624a00cda9cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New releases'])[1]/preceding::tp-yt-iron-icon[11]</value>
      <webElementGuid>1b48048d-7821-4acd-b3ec-129d84ef82e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tp-yt-iron-icon</value>
      <webElementGuid>6cb41d29-b3c7-4c70-bbce-a3b16997dcee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//tp-yt-iron-icon[@id = 'icon']</value>
      <webElementGuid>800b4d7a-d97a-486b-989e-dbc158f52740</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
