<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>page_title_moods</name>
   <tag></tag>
   <elementGuidId>0ce6a14f-8384-4e8e-a63f-509b1a968af1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='header']/ytmusic-header-renderer/h2/yt-formatted-string</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>yt-formatted-string.title.style-scope.ytmusic-header-renderer</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>yt-formatted-string</value>
      <webElementGuid>e098ae14-743a-4258-8eaf-35c4b0755c9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>title style-scope ytmusic-header-renderer</value>
      <webElementGuid>b5728ad8-3743-4bc3-a114-cbfa8a667ceb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Moods &amp; genres</value>
      <webElementGuid>1d9bdea5-e1a0-441b-9875-c89702f0a539</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;browse-page&quot;)/div[@class=&quot;background-gradient style-scope ytmusic-browse-response&quot;]/div[@id=&quot;header&quot;]/ytmusic-header-renderer[@class=&quot;style-scope ytmusic-browse-response&quot;]/h2[@class=&quot;style-scope ytmusic-header-renderer&quot;]/yt-formatted-string[@class=&quot;title style-scope ytmusic-header-renderer&quot;]</value>
      <webElementGuid>26a0856e-1004-4a98-a79e-7510e9230669</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='header']/ytmusic-header-renderer/h2/yt-formatted-string</value>
      <webElementGuid>57f8c208-525e-4bca-892b-4522312d3675</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign in'])[1]/following::yt-formatted-string[1]</value>
      <webElementGuid>f3968cf2-a00c-4dfd-892c-ccbc1c7e4dad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Library'])[1]/following::yt-formatted-string[1]</value>
      <webElementGuid>da6c6ecf-8ee9-487b-b23b-a283a1330558</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Moods &amp; moments'])[1]/preceding::yt-formatted-string[1]</value>
      <webElementGuid>149e665b-2437-4529-88c2-cf1edbf89a64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chill'])[1]/preceding::yt-formatted-string[2]</value>
      <webElementGuid>3a720a75-d8bf-4180-8eee-0cacfb9d234b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Moods &amp; genres']/parent::*</value>
      <webElementGuid>a7a0b8d3-2133-45f5-b9ac-bfc82dbd05d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2/yt-formatted-string</value>
      <webElementGuid>79e2efb0-4820-42ff-9523-378745aa3b2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//yt-formatted-string[(text() = 'Moods &amp; genres' or . = 'Moods &amp; genres')]</value>
      <webElementGuid>072622e4-7745-4849-9f8f-f6d83a739728</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
