<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>page_title_charts</name>
   <tag></tag>
   <elementGuidId>d8997311-ddde-4cff-8c71-04d9c87e662b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='header']/ytmusic-header-renderer/h2/yt-formatted-string</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>yt-formatted-string.title.style-scope.ytmusic-header-renderer</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>yt-formatted-string</value>
      <webElementGuid>5d29fa8d-d3fc-4f91-8ffe-bbf21b65b087</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>title style-scope ytmusic-header-renderer</value>
      <webElementGuid>17d0a5b3-03ff-4747-b1da-269141d7afaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Charts</value>
      <webElementGuid>3de485e0-e228-4c7b-adb3-e6cac419027d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;browse-page&quot;)/div[@class=&quot;background-gradient style-scope ytmusic-browse-response&quot;]/div[@id=&quot;header&quot;]/ytmusic-header-renderer[@class=&quot;style-scope ytmusic-browse-response&quot;]/h2[@class=&quot;style-scope ytmusic-header-renderer&quot;]/yt-formatted-string[@class=&quot;title style-scope ytmusic-header-renderer&quot;]</value>
      <webElementGuid>61190e08-e251-4874-9700-a1423591567d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='header']/ytmusic-header-renderer/h2/yt-formatted-string</value>
      <webElementGuid>87b8875e-dcb7-47c7-98cf-606b09682cd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign in'])[1]/following::yt-formatted-string[1]</value>
      <webElementGuid>30b13410-9b4d-4d38-9d80-222b47527396</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Library'])[1]/following::yt-formatted-string[1]</value>
      <webElementGuid>8d2f1eb0-563b-4074-af83-6caea98966ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Indonesia'])[1]/preceding::yt-formatted-string[1]</value>
      <webElementGuid>72052474-3582-41f5-bd04-f25fca18e307</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Top music videos'])[1]/preceding::yt-formatted-string[3]</value>
      <webElementGuid>a92dbdb9-87af-4bcc-9b8f-12031f6f65a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Charts']/parent::*</value>
      <webElementGuid>4362d905-6305-4673-99a9-ab8471129974</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2/yt-formatted-string</value>
      <webElementGuid>06d2fa2c-634c-4cd4-a899-86ce27e51195</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//yt-formatted-string[(text() = 'Charts' or . = 'Charts')]</value>
      <webElementGuid>599d761a-30a4-4056-91cd-ebd07795265b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
