<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>quick_pick_song</name>
   <tag></tag>
   <elementGuidId>b2e729bd-21c5-4a46-abdb-17665cb44e32</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ytmusic-play-button-renderer[@id='play-button']/div/yt-icon</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>yt-icon.icon.style-scope.ytmusic-play-button-renderer</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>yt-icon</value>
      <webElementGuid>e97659dc-dd38-482e-9b9a-46d59c69771f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon style-scope ytmusic-play-button-renderer</value>
      <webElementGuid>400fd7a6-97a2-4d45-83ac-68d6c907d250</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;browse-page&quot;)/div[@class=&quot;background-gradient style-scope ytmusic-browse-response&quot;]/ytmusic-section-list-renderer[@class=&quot;style-scope ytmusic-browse-response&quot;]/div[@id=&quot;contents&quot;]/ytmusic-carousel-shelf-renderer[@class=&quot;style-scope ytmusic-section-list-renderer fullbleed&quot;]/div[@class=&quot;ytmusic-shelf style-scope ytmusic-carousel-shelf-renderer&quot;]/ytmusic-carousel[@id=&quot;ytmusic-carousel&quot;]/div[@id=&quot;items-wrapper&quot;]/ul[@id=&quot;items&quot;]/ytmusic-responsive-list-item-renderer[@class=&quot;style-scope ytmusic-carousel&quot;]/div[@class=&quot;left-items style-scope ytmusic-responsive-list-item-renderer&quot;]/ytmusic-item-thumbnail-overlay-renderer[@class=&quot;thumbnail-overlay style-scope ytmusic-responsive-list-item-renderer&quot;]/div[@id=&quot;content&quot;]/ytmusic-play-button-renderer[@id=&quot;play-button&quot;]/div[@class=&quot;content-wrapper style-scope ytmusic-play-button-renderer&quot;]/yt-icon[@class=&quot;icon style-scope ytmusic-play-button-renderer&quot;]</value>
      <webElementGuid>5b668ab1-ad3d-48b7-a80d-4bb90a87230a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ytmusic-play-button-renderer[@id='play-button']/div/yt-icon</value>
      <webElementGuid>f15384b8-3118-42e5-9d2b-be93cf93b013</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign in'])[1]/following::yt-icon[1]</value>
      <webElementGuid>e68ca397-22eb-41f1-b2f2-a95e39dc62ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Library'])[1]/following::yt-icon[1]</value>
      <webElementGuid>6685185b-fcd5-4447-9714-0be8bb7552e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dalam Sepiku Kaulah Candaku - Cintaku (feat. Gisma Wandira)'])[1]/preceding::yt-icon[2]</value>
      <webElementGuid>1e0b675a-7137-4966-a678-156111f4b920</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Andra Respati'])[1]/preceding::yt-icon[4]</value>
      <webElementGuid>f8dd54f5-3e19-4ca8-9282-7c3422d6ddd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ytmusic-play-button-renderer/div/yt-icon</value>
      <webElementGuid>b4411b5b-e2ea-40ea-9563-59136cd1295c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
